[project]
name = "opentps-core"
version = "3.0.1"
description = "Core library for OpenTPS - open source treatment planning system"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.12,<3.13"
authors = [
    {name = "Sylvain Deffet", email = "sylvaindeffet@gmail.com"},
    {name = "Damien Dasnoy", email = "damien.dasnoy@uclouvain.be"},
    {name = "Valentin Hamaide", email = "valentin.hamaide@uclouvain.be"},
    {name = "Guillaume Janssens", email = "guillaume.janssens@iba-group.com"},
    {name = "Kevin Souris", email = "kevin.souris@iba-group.com"},
    {name = "Sophie Wuyckens", email = "sophie.wuyckens@uclouvain.be"},
]
dependencies = [
    "cachecontrol",
    "numpy>=2.0.0",
    "Pillow>=10.0.0",
    "pydicom>=3.0.1",
    "SimpleITK>=2.2.1",
    "sparse-dot-mkl>=0.9.6; platform_machine == 'x86_64' or platform_machine == 'AMD64'",
    "setuptools>=67.8.0",
    "pandas>=2.2.0",
    "requests",
    "scikit-image",
    "pymedphys>=0.41.0",
    "nibabel>=5.0.0,<6.0.0",
    "pip",  # Required because code imports from pip._internal.utils.appdirs (bad practice, should be fixed upstream)
]

[project.urls]
Homepage = "http://opentps.org/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["opentps"]
